version: '3.1'

services:
  api:
    build: './api'
    container_name: crud_people_api
    ports: ['3000:3000']
    expose: ['3000']
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=crudpeople
    links:
      - db
    volumes: 
      - ./api:/usr/src/crud-people
    
  db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports: 
      - 27017:27017